#!/bin/sh
# dc1-h2: eth0 = OOB management (10.3.0.51), eth1 = ce1 eth4 (dc1 LAN 172.21.1.0/24, gateway 172.21.1.1)
hostname dc1-h2
ip link set eth0 up
ip addr add 10.3.0.51/24 dev eth0
ip link set eth1 up
ip addr add 172.21.1.2/24 dev eth1
ip route replace default via 172.21.1.1 dev eth1
