#!/bin/sh
# dc2-h2: eth0 = OOB management (10.3.0.52), eth1 = ce2 eth4 (dc2 LAN 172.21.2.0/24, gateway 172.21.2.1)
hostname dc2-h2
ip link set eth0 up
ip addr add 10.3.0.52/24 dev eth0
ip link set eth1 up
ip addr add 172.21.2.2/24 dev eth1
ip route replace default via 172.21.2.1 dev eth1
