#!/bin/sh
# dc4-h1: eth0 = OOB management (10.3.0.44), eth1 = ce4 eth2 (dc4 LAN 172.20.4.0/24, gateway 172.20.4.1)
hostname dc4-h1
ip link set eth0 up
ip addr add 10.3.0.44/24 dev eth0
ip link set eth1 up
ip addr add 172.20.4.2/24 dev eth1
ip route replace default via 172.20.4.1 dev eth1
