#!/bin/sh
# dc3-h1: eth0 = OOB management (10.3.0.43), eth1 = ce3 eth2 (dc3 LAN 172.20.3.0/24, gateway 172.20.3.1)
hostname dc3-h1
ip link set eth0 up
ip addr add 10.3.0.43/24 dev eth0
ip link set eth1 up
ip addr add 172.20.3.2/24 dev eth1
ip route replace default via 172.20.3.1 dev eth1
