#!/bin/sh
# dc4-h2: eth0 = OOB management (10.3.0.54), eth1 = ce4 eth4 (dc4 LAN 172.21.4.0/24, gateway 172.21.4.1)
hostname dc4-h2
ip link set eth0 up
ip addr add 10.3.0.54/24 dev eth0
ip link set eth1 up
ip addr add 172.21.4.2/24 dev eth1
ip route replace default via 172.21.4.1 dev eth1
